### ISSUE TITLE
Links showing as separate text and label in HTML

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rsd#13] opened 2018-07-11 09:37 UTC
For example, this line
```asciidoc
https://docs.oracle.com/cd/E19563-01/819-4429/acmct/index.html[`imsexport` command-line tool]
```
Is shown as this:

![screen shot 2018-07-11 at 5 36 01 pm](https://user-images.githubusercontent.com/11865/42563475-e9dc263c-8530-11e8-8829-88e6f2e526cc.png)

There are 2 issues:

1. the link is not being combined with the label
2. the monospace text is being rendered as `<tt>blah</tt>`

**Comment by opoudjis** [comment] 2018-07-11 13:03
I can't fully replicate: I'm getting 2 but not 1.

**Comment by ronaldtse** [comment] 2018-07-11 13:06
I'm still getting 1. How about try this?

```asciidoc
Let's use this tool:

* https://github.com/riboseinc/ribose-ruby[Ribose Ruby API]
```

**Comment by opoudjis** [comment] 2018-07-11 13:29
Fixed in asciidoctor-iso and isodoc:

````
= Doc
:title-intro-en: Information technology
:title-main-en: Security techniques -- Encryption algorithms
:title-part-en: Part 5: Identity-based ciphers

== Foreword 

Let's use this tool:

* https://github.com/riboseinc/ribose-ruby[Ribose Ruby API]
* https://github.com/riboseinc/ribose-ruby[`Ribose` Ruby API]
````

````<sections>
  <clause id="_foreword" inline-header="false" obligation="normative"><title>Foreword</title><p id="_713b447d-bd01-4542-9b8e-2a4b8e542be1">Let?~@~Ys use this tool:</p>
<ul id="_8cedd2b1-e437-4fc0-a380-cdd38ca31289">
  <li>
    <p id="_d335e0fe-91ee-41c6-8c5c-a5990c954b1b">
      <link target="https://github.com/riboseinc/ribose-ruby">Ribose Ruby API</link>
    </p>
  </li>
  <li>
    <p id="_54e19a89-3c6a-4cf0-bcb1-2752373a964f">
      <link target="https://github.com/riboseinc/ribose-ruby"><tt>Ribose</tt> Ruby API</link>
    </p>
  </li>
</ul></clause>
</sections>
````

````
      <div id="_foreword">
        <h1>1.&#xA0; Foreword</h1>
        <p id="_713b447d-bd01-4542-9b8e-2a4b8e542be1">Let&#x2019;s use this tool:</p>
        <ul>
  <li>
    <p id="_d335e0fe-91ee-41c6-8c5c-a5990c954b1b">
      <a href="https://github.com/riboseinc/ribose-ruby">Ribose Ruby API</a>
    </p>
  </li>
  <li>
    <p id="_54e19a89-3c6a-4cf0-bcb1-2752373a964f">
      <a href="https://github.com/riboseinc/ribose-ruby"><tt>Ribose</tt> Ruby API</a>
    </p>
  </li>
</ul>
      </div>
````

**Comment by ronaldtse** [comment] 2018-07-11 19:02
Somehow it's not fully fixed over here.

```asciidoc
* https://github.com/riboseinc/ribose-ruby[Ribose Ruby API]
```

```html
<ul>
  <li>
    <p id="_3881b654-ef9e-40bf-ae56-37f26e11d82e">
      <a href="https://github.com/riboseinc/ribose-ruby">https://github.com/riboseinc/ribose-ruby</a>Ribose Ruby API
    </p>
  </li>
</ul>
```

**Comment by opoudjis** [comment] 2018-07-11 23:41
Send me your .xml and your .html.

**Comment by opoudjis** [comment] 2018-07-12 04:04
This turns out to be a reprise of the issue I had earlier with iso-bib-item output read into asciidoctor-iso: https://github.com/riboseinc/asciidoctor-iso/issues/187. Nokogiri Builder works fine with "link" as a tag; but when I read text in and convert it to XML through Nokogiri::XML, Nokogiri closes the link tag before the link contents. I could not resolve the issue, and after a few hours decided to just rename the tag in biblio.

But I am not getting this issue in asciidoctor-iso now with link tags, and Ronald is. We are both running 1.8.4 Nokogiri. He is running libxml 2.9.7, I am running libxml 2.9.2

**Comment by opoudjis** [comment] 2018-07-12 04:13
@ronaldtse To start with, what do you get in irb with 

````
require "nokogiri"
Nokogiri::XML("<link>ABC</link>").to_xml
````

**Comment by ronaldtse** [comment] 2018-07-12 04:13
```ruby
irb(main):001:0> require "nokogiri"
=> true
irb(main):002:0> Nokogiri::XML("<link>ABC</link>").to_xml
=> "<?xml version=\"1.0\"?>\n<link>ABC</link>\n"
```

**Comment by opoudjis** [comment] 2018-07-12 04:16
And `Nokogiri::XML("<link target='http://example.com'>ABC</link>").to_xml`?

**Comment by ronaldtse** [comment] 2018-07-12 04:33
```ruby
irb(main):003:0> Nokogiri::XML("<link target='http://example.com'>ABC</link>").to_xml
=> "<?xml version=\"1.0\"?>\n<link target=\"http://example.com\">ABC</link>\n"
```

**Comment by ronaldtse** [comment] 2018-07-12 04:34
I noticed that an email will already cause this issue:

```asciidoc
hello@example.com
```

```xml
  <p id="_768d70a1-9611-432b-89ca-2f0f44994ffe">
    <link target="mailto:hello@example.com"/>mailto:hello@example.com
  </p>
```

**Comment by opoudjis** [comment] 2018-07-12 05:01
Yes, emails are treated as hyperlinks by Asciidoctor.

This... is bad, because I really don't understand how to reproduce this. Next step:

Create a new Asciidoctor document test.adoc:

````
= Doc
:title-intro-en: Information technology
:title-main-en: Security techniques -- Encryption algorithms
:title-part-en: Part 5: Identity-based ciphers

== Foreword 

Let's use this tool:

* https://github.com/riboseinc/ribose-ruby[Ribose Ruby API]
* https://github.com/riboseinc/ribose-ruby[`Ribose` Ruby API]
````

Process it with asciidoctor --trace -b iso -r 'asciidoctor-iso' test.adoc

Tell me what happens in the test.xml. No bundle, just running in your asciidoctor-iso local github repository instance.

**Comment by ronaldtse** [comment] 2018-07-13 03:44
XML:
```xml
<ul id="_0cbb177e-06d4-450d-86f8-0073ed99845f">
  <li>
    <p id="_95801fc2-c728-4fda-b2a6-97cb8441dafc">
      <link target="https://github.com/riboseinc/ribose-ruby">Ribose Ruby API</link>
    </p>
  </li>
  <li>
    <p id="_a2a20d20-6b16-498b-bc71-aa466725727e">
      <link target="https://github.com/riboseinc/ribose-ruby">&lt;tt&gt;Ribose&lt;/tt&gt; Ruby API</link>
    </p>
  </li>
</ul>
```

**Comment by opoudjis** [comment] 2018-07-14 10:57
Now that does not reflect current code. Please pull and try again.

````
<ul id="_40068906-633a-4f0a-a932-45e3577163c5">
  <li>
    <p id="_9ff26bf9-9266-4c9c-b0f8-4ad3475259c2">
      <link target="https://github.com/riboseinc/ribose-ruby">Ribose Ruby API</link>
    </p>
  </li>
  <li>
    <p id="_e4745dd3-07d7-4711-8c62-5915ae41c7ec">
      <link target="https://github.com/riboseinc/ribose-ruby"><tt>Ribose</tt> Ruby API</link>
    </p>
  </li>
</ul>
````

**Comment by ronaldtse** [comment] 2018-07-15 03:14
Error in updating the gems:

```ruby
Bundler could not find compatible versions for gem "isodoc":
  In Gemfile:
    isodoc

    asciidoctor-rsd was resolved to 0.3.2, which depends on
      isodoc (>= 0.8.4)

Could not find gem 'isodoc (>= 0.8.4)', which is required by gem 'asciidoctor-rsd', in any of the relevant
sources:
  https://github.com/riboseinc/isodoc (at master@8cdfe67)
```

**Comment by opoudjis** [comment] 2018-07-15 22:30
isodoc 0.8.4 is pushed both to github and as a gem.

**Comment by ronaldtse** [comment] 2018-07-31 10:46
Similar issue persists. 

x.adoc
```adoc
= Doc
:title-intro-en: Information technology
:title-main-en: Security techniques -- Encryption algorithms
:title-part-en: Part 5: Identity-based ciphers

== Foreword

Let's use this tool:

* https://github.com/riboseinc/ribose-ruby[Ribose Ruby API]
* https://github.com/riboseinc/ribose-ruby[`Ribose` Ruby API]


For further enquiries, please contact myemail@example.com
```

Command: `bundle exec metanorma -t rsd -x xml,html x.adoc`

x.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rsd-standard xmlns="https://open.ribose.com/standards/rsd">
<bibdata type="standard">
  
  
  <contributor>
    <role type="author"/>
    <organization>
      <name>Ribose</name>
    </organization>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Ribose</name>
    </organization>
  </contributor>
  
  <script>Latn</script>
  
  <copyright>
    <from>2018</from>
    <owner>
      <organization>
        <name>Ribose</name>
      </organization>
    </owner>
  </copyright>
  <editorialgroup>
    <committee/>
  </editorialgroup>
</bibdata>
<sections>
  <clause id="_foreword" obligation="normative"><title>Foreword</title><p id="_a1edd5de-ad1e-43d5-ad7a-f6abce07c884">Let’s use this tool:</p>
<ul id="_36db2563-cadb-4fb7-a37c-899d33bb6099">
  <li>
    <p id="_57c8e743-2923-4ab8-8146-3f1fb4af995b">
      <link target="https://github.com/riboseinc/ribose-ruby">Ribose Ruby API</link>
    </p>
  </li>
  <li>
    <p id="_a0466502-31ba-4cd6-b788-3c85365caa65">
      <link target="https://github.com/riboseinc/ribose-ruby"><tt>Ribose</tt> Ruby API</link>
    </p>
  </li>
</ul>
<p id="_b7783ede-9ace-4d39-9dd2-9c16ed525f86">For further enquiries, please contact <link target="mailto:myemail@example.com"/></p></clause>
</sections>
</rsd-standard>
```

Rendered HTML:
![screen shot 2018-07-31 at 6 44 32 pm](https://user-images.githubusercontent.com/11865/43455228-c948ff5a-94f1-11e8-991f-da1ef8f34b2d.png)


Notice the "mailto:myemail@example.com" is rendered without content. The link content should be `myemail@example.com` not `mailto:myemail@example.com`.

**Comment by opoudjis** [comment] 2018-07-31 23:00
Replicated, though I note with some satisfaction that the major issue has gone away. This will be simply a matter of stripping initial mailto: when there is no rendering text given. Implementing.

**Comment by opoudjis** [comment] 2018-07-31 23:11
Fixed in isodoc

**Closed by opoudjis** 2018-07-31 23:11 UTC
Labels: bug

**Comment by ronaldtse** [comment] 2018-08-01 00:15
@opoudjis does this mean that isodoc will need to now understand URI syntax?

For example, if I have "mailto:xxx" then it displays "xxx", and if "https://xxx" then it shows "https://xxx"?

**Comment by opoudjis** [comment] 2018-08-01 08:07
It's a one liner, it strips mailto from the prefix if there is no link text. Surely no big deal.
